Revert "[IStats] Provided VTS to validate VendorAtom logging APIs"
Revert submission 21471579-istats-vts

Reason for revert: Breaks build with

  error: unknown type name 'BytesField'

Though this is not a reliable error, due to an incremental build issue.

Reverted changes: /q/submissionid:21471579-istats-vts

Change-Id: I14d7af5ea10726fe03518f68b099a95d68d15a86